### ISSUE TITLE
System.Windows.WindowでToolTipを表示するときにエラーが発生する

### ISSUE THREAD

**Issue by Yuku1A** [nishy2000/MetroRadiance#1]
環境:Windows10 20H2 (19042.746)、.NET Core 3.1、MetroRadiance.Fork 3.0.0-alpha04
MetroWindowではなく、System.Windows.Windowを使用している環境で
Visual Studio 2019(16.8.4)でデバッグしているときにツールチップを表示しようとすると以下のエラーが出力される
`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MetroRadiance.UI.Controls.WindowCompat', AncestorLevel='1''. BindingExpression:Path=DpiScaleTransform; DataItem=null; target element is 'Border' (Name='Border'); target property is 'LayoutTransform' (type 'Transform')`

追記：MetroRadiance.Fork 3.0.0でも発生します

**Comment by nishy2000** [comment]
報告ありがとうございます。次回のリリースで反映します。
